# SwiftLint Configuration

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - explicit_init
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - fatal_error_message
  - first_where

included:
  - AirFit

excluded:
  - Pods
  - Carthage
  - AirFit/Tests

colon:
  flexible_right_spacing: true
comma:
  flexible_spacing: true
cyclomatic_complexity:
  warning: 15
  error: 25
file_length:
  warning: 500
  error: 800
function_body_length:
  warning: 60
  error: 100
type_body_length:
  warning: 300
  error: 500
reporter: "xcode"
