name: AirFit
options:
  bundleIdPrefix: com.airfit
  deploymentTarget:
    iOS: "26.0"
    watchOS: "26.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "26.0"
  WATCHOS_DEPLOYMENT_TARGET: "26.0"
  ENABLE_STRICT_CONCURRENCY: YES
  SWIFT_STRICT_CONCURRENCY: complete
  DEAD_CODE_STRIPPING: YES

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  AirFit:
    type: application
    platform: iOS
    sources:
      - path: AirFit/App
      - path: AirFit/Models
      - path: AirFit/Views
      - path: AirFit/Services
      - path: AirFit/Speech
      - path: AirFit/Utilities
      - path: AirFit/Assets.xcassets

    dependencies:
      - package: WhisperKit
      - target: AirFitWidget

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app
      INFOPLIST_FILE: AirFit/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFit/AirFit.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: "1"

  AirFitWatch:
    type: application
    platform: watchOS
    sources:
      - path: AirFitWatch
    dependencies:
      - target: AirFitWatchComplications
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app.watchkitapp
      INFOPLIST_FILE: AirFitWatch/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFitWatch/AirFitWatch.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SKIP_INSTALL: NO
      WATCHOS_DEPLOYMENT_TARGET: "26.0"
      # Embedding configuration
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

  AirFitWatchComplications:
    type: app-extension
    platform: watchOS
    sources:
      - path: AirFitWatchComplications
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app.watchkitapp.complications
      INFOPLIST_FILE: AirFitWatchComplications/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFitWatchComplications/AirFitWatchComplications.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      SKIP_INSTALL: YES
      WATCHOS_DEPLOYMENT_TARGET: "26.0"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  AirFitWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: AirFitWidget
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app.widget
      INFOPLIST_FILE: AirFitWidget/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFitWidget/AirFitWidget.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      SKIP_INSTALL: YES
      IPHONEOS_DEPLOYMENT_TARGET: "26.0"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

schemes:
  AirFit:
    build:
      targets:
        AirFit: all
        AirFitWidget: all
        AirFitWatch: all
        AirFitWatchComplications: all
    run:
      config: Debug
  AirFit-iOS:
    build:
      targets:
        AirFit: all
        AirFitWidget: all
    run:
      config: Debug
    archive:
      config: Release
  AirFitWatch:
    build:
      targets:
        AirFitWatch: all
        AirFitWatchComplications: all
    run:
      config: Debug
