name: AirFit
options:
  bundleIdPrefix: com.airfit
  deploymentTarget:
    iOS: "26.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "26.0"
  ENABLE_STRICT_CONCURRENCY: YES
  SWIFT_STRICT_CONCURRENCY: complete
  DEAD_CODE_STRIPPING: YES

targets:
  AirFit:
    type: application
    platform: iOS
    sources:
      - path: AirFit/App
      - path: AirFit/Models
      - path: AirFit/Views
      - path: AirFit/Services
      - path: AirFit/Utilities
      - path: AirFit/Assets.xcassets

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app
      INFOPLIST_FILE: AirFit/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFit/AirFit.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: "1"

schemes:
  AirFit:
    build:
      targets:
        AirFit: all
    run:
      config: Debug
