name: AirFit
options:
  bundleIdPrefix: com.airfit
  deploymentTarget:
    iOS: "26.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  groupOrdering:
    - pattern: "Application"
      order: [AirFitApp.swift, ContentView.swift]
    - pattern: "Core"
      order: [Constants, DI, Enums, Extensions, Models, Protocols, Theme, Utilities, Views]
    - pattern: "Data"
      order: [Extensions, Managers, Migrations, Models]
    - pattern: "Modules"
      order: [AI, Chat, Dashboard, FoodTracking, Notifications, Onboarding, Settings, Workouts]
    - pattern: "Services"
      order: [AI, Analytics, Cache, Context, Goals, Health, Monitoring, Network, Security, Speech, User, Weather]

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "26.0"
  ENABLE_STRICT_CONCURRENCY: YES
  SWIFT_STRICT_CONCURRENCY: complete
  DEAD_CODE_STRIPPING: YES
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  SWIFT_EMIT_LOC_STRINGS: YES

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: "0.9.0"

fileGroups:
  - AirFit/Resources

configs:
  Debug:
    name: Debug
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      ENABLE_TESTABILITY: YES
      GCC_OPTIMIZATION_LEVEL: "0"
      SWIFT_COMPILATION_MODE: "incremental"
      
  Release:
    name: Release
    settings:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      ENABLE_TESTABILITY: NO
      GCC_OPTIMIZATION_LEVEL: "s"
      SWIFT_COMPILATION_MODE: "wholemodule"
      VALIDATE_PRODUCT: YES

targets:
  AirFit:
    type: application
    platform: iOS
    sources:
      # Application Layer
      - path: AirFit/Application
        createIntermediateGroups: true
      
      # Core Layer - Foundation of the app
      - path: AirFit/Core
        createIntermediateGroups: true
      
      # Data Layer - Models and persistence
      - path: AirFit/Data
        createIntermediateGroups: true
      
      # Modules - Feature modules
      - path: AirFit/Modules
        createIntermediateGroups: true
      
      # Services - Business logic and external integrations
      - path: AirFit/Services
        createIntermediateGroups: true
      
      # Exclude test files and other non-source files
      - path: AirFit
        excludes:
          - "**/*.md"
          - "**/.*"
          - "AirFitTests/**"
          - "AirFitUITests/**"
          - "Info.plist"
          - "Resources/**/*.json"  # Include json files as resources, not sources
          # Cleanup: exclude backup and non-source artifacts so they aren't treated as resources
          - "**/*.bak"
          - "**/*.backup"
          - "**/*.backup.*"
          - "**/*.log"
          - "**/*.html"
          - "**/.DS_Store"
          - "build/**"
          - "Docs/**"
          - "node_modules/**"
    
    resources:
      - path: AirFit/Assets.xcassets
      - path: AirFit/Resources
        optional: true
      - path: AirFit/Info.plist
        optional: true
    
    dependencies:
      - package: WhisperKit
    
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app
      INFOPLIST_FILE: AirFit/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFit/AirFit.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
      SWIFT_EMIT_LOC_STRINGS: YES
      TARGETED_DEVICE_FAMILY: "1"
      SUPPORTS_MACCATALYST: NO
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      DEAD_CODE_STRIPPING: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      SKIP_INSTALL: NO
      DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING: YES
      ENABLE_APP_INTENTS_DEPLOYMENT_AWARE_PROCESSING: NO
    
    preBuildScripts:
      - script: |
          # Ensure Info.plist exists
          if [ ! -f "${SRCROOT}/AirFit/Info.plist" ]; then
            echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>$(DEVELOPMENT_LANGUAGE)</string>
            <key>CFBundleExecutable</key>
            <string>$(EXECUTABLE_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>$(PRODUCT_NAME)</string>
            <key>CFBundlePackageType</key>
            <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSRequiresIPhoneOS</key>
            <true/>
            <key>UIApplicationSceneManifest</key>
            <dict>
              <key>UIApplicationSupportsMultipleScenes</key>
              <true/>
            </dict>
            <key>UILaunchScreen</key>
            <dict/>
            <key>MinimumOSVersion</key>
            <string>26.0</string>
            <key>UIRequiredDeviceCapabilities</key>
            <array>
              <string>arm64</string>
            </array>
            <key>UISupportedInterfaceOrientations</key>
            <array>
              <string>UIInterfaceOrientationPortrait</string>
              <string>UIInterfaceOrientationLandscapeLeft</string>
              <string>UIInterfaceOrientationLandscapeRight</string>
            </array>
            <key>NSHealthShareUsageDescription</key>
            <string>AirFit needs access to your health data to provide personalized fitness coaching and track your progress.</string>
            <key>NSHealthUpdateUsageDescription</key>
            <string>AirFit needs permission to save workout data to Apple Health.</string>
            <key>NSMicrophoneUsageDescription</key>
            <string>AirFit needs access to your microphone for voice input during coaching sessions.</string>
            <key>NSSpeechRecognitionUsageDescription</key>
            <string>AirFit uses speech recognition to process your voice commands and coaching responses.</string>
          </dict>
          </plist>' > "${SRCROOT}/AirFit/Info.plist"
          fi
        name: "Generate Info.plist if needed"
        showEnvVars: false
        outputFiles:
          - "${SRCROOT}/AirFit/Info.plist"

  AirFitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AirFit/AirFitTests
        createIntermediateGroups: true
    dependencies:
      - target: AirFit
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/AirFit.app/AirFit
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: NO
      SWIFT_STRICT_CONCURRENCY: minimal

  AirFitUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: AirFit/AirFitUITests
        createIntermediateGroups: true
    dependencies:
      - target: AirFit
    settings:
      TEST_TARGET_NAME: AirFit
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete


schemes:
  AirFit:
    build:
      targets:
        AirFit: all
        AirFitTests: [test]
        AirFitUITests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: AIRFIT_DEBUG_MODE
          value: "1"
          isEnabled: true
    test:
      config: Debug
      parallelizeBuildables: true
      targets:
        - name: AirFitTests
          parallelizable: true
          randomExecutionOrder: true
      testPlans:
        - path: AirFit-Unit.xctestplan
          defaultPlan: true
        - path: AirFit-Integration.xctestplan
        - path: AirFit-UI.xctestplan
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  AirFit-TestFlight:
    build:
      targets:
        AirFit: all
      config: Release
      postActions:
        - script: |
            # Increment build number
            BUILD_NUMBER=$(date +%Y%m%d%H%M)
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          name: "Increment Build Number"
          settingsTarget: AirFit
    run:
      config: Release
    test:
      config: Release
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
      revealArchiveInOrganizer: true
