name: AirFit
options:
  bundleIdPrefix: com.airfit
  deploymentTarget:
    iOS: "26.0"
    watchOS: "11.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "26.0"
  WATCHOS_DEPLOYMENT_TARGET: "11.0"
  ENABLE_STRICT_CONCURRENCY: YES
  SWIFT_STRICT_CONCURRENCY: complete
  DEAD_CODE_STRIPPING: YES

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  AirFit:
    type: application
    platform: iOS
    sources:
      - path: AirFit/App
      - path: AirFit/Models
      - path: AirFit/Views
      - path: AirFit/Services
      - path: AirFit/Speech
      - path: AirFit/Utilities
      - path: AirFit/Assets.xcassets

    dependencies:
      - package: WhisperKit
      # - target: AirFitWatch  # Uncomment when watchOS SDK is installed

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app
      INFOPLIST_FILE: AirFit/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFit/AirFit.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      TARGETED_DEVICE_FAMILY: "1"

  AirFitWatch:
    type: application
    platform: watchOS
    sources:
      - path: AirFitWatch
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app.watchkitapp
      INFOPLIST_FILE: AirFitWatch/Info.plist
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 2H43Q8Y3CR
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      SKIP_INSTALL: NO
      WATCHOS_DEPLOYMENT_TARGET: "11.0"

schemes:
  AirFit:
    build:
      targets:
        AirFit: all
        # AirFitWatch: all  # Uncomment when watchOS SDK is installed
    run:
      config: Debug
  AirFitWatch:
    build:
      targets:
        AirFitWatch: all
    run:
      config: Debug
