name: AirFit
options:
  bundleIdPrefix: com.airfit
  deploymentTarget:
    iOS: "18.0"
    watchOS: "11.0"
  developmentLanguage: en
  xcodeVersion: "16.0"

settings:
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "18.0"
  WATCHOS_DEPLOYMENT_TARGET: "11.0"
  ENABLE_STRICT_CONCURRENCY: YES
  SWIFT_STRICT_CONCURRENCY: complete

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  AirFit:
    type: application
    platform: iOS
    sources:
      - path: AirFit
        includes:
          - "**/*.swift"
        excludes:
          - "**/*.md"
          - "**/.*"
          - "AirFitTests/**"
          - "AirFitUITests/**"
      - AirFit/Modules/Onboarding/Models/OnboardingModels.swift
      - AirFit/Modules/Onboarding/ViewModels/OnboardingViewModel.swift
      - AirFit/Modules/Onboarding/Views/OnboardingFlowView.swift
      - AirFit/Modules/Onboarding/Views/LifeSnapshotView.swift
      - AirFit/Modules/Onboarding/Views/OpeningScreenView.swift
      - AirFit/Modules/Onboarding/Views/CoachProfileReadyView.swift
      - AirFit/Modules/Onboarding/Views/CoreAspirationView.swift
      - AirFit/Modules/Onboarding/Views/EngagementPreferencesView.swift
      - AirFit/Modules/Onboarding/Views/GeneratingCoachView.swift
      - AirFit/Modules/Onboarding/Views/OnboardingNavigationButtons.swift
      - AirFit/Modules/Onboarding/Views/MotivationalAccentsView.swift
      - AirFit/Modules/Onboarding/Views/SleepAndBoundariesView.swift
      - AirFit/Modules/Onboarding/Views/HealthKitAuthorizationView.swift
      - AirFit/Modules/Onboarding/Views/CoachingStyleView.swift
      - AirFit/Modules/Onboarding/Services/OnboardingService.swift
      - AirFit/Modules/Onboarding/Services/OnboardingServiceProtocol.swift
      - AirFit/Modules/Onboarding/Coordinators/OnboardingCoordinator.swift
      # Data Layer Models (CRITICAL: XcodeGen nesting bug)
      - AirFit/Data/Models/OnboardingProfile.swift
      - AirFit/Data/Models/User.swift
      - AirFit/Data/Models/CoachMessage.swift
      - AirFit/Data/Models/FoodEntry.swift
      - AirFit/Data/Models/FoodItem.swift
      - AirFit/Data/Models/MealTemplate.swift
      - AirFit/Data/Models/FoodItemTemplate.swift
      - AirFit/Data/Models/WorkoutTemplate.swift
      - AirFit/Data/Models/HealthKitSyncRecord.swift
      - AirFit/Data/Models/Workout.swift
      - AirFit/Data/Models/DailyLog.swift
      - AirFit/Data/Models/ChatMessage.swift
      - AirFit/Data/Models/ChatAttachment.swift
      - AirFit/Data/Models/Exercise.swift
      - AirFit/Data/Models/ExerciseTemplate.swift
      - AirFit/Data/Models/ExerciseSet.swift
      - AirFit/Data/Models/NutritionData.swift
      - AirFit/Data/Models/ChatSession.swift
      - AirFit/Data/Models/SetTemplate.swift
      # Data Layer Extensions & Managers (CRITICAL: XcodeGen nesting bug)
      - AirFit/Data/Extensions/FetchDescriptor+Extensions.swift
      - AirFit/Data/Extensions/ModelContainer+Testing.swift
      - AirFit/Data/Managers/DataManager.swift
      - AirFit/Data/Migrations/SchemaV1.swift
      # Core Layer Files (CRITICAL: XcodeGen nesting bug)
      - AirFit/Core/Constants/APIConstants.swift
      - AirFit/Core/Constants/AppConstants.swift
      - AirFit/Core/Enums/GlobalEnums.swift
      - AirFit/Core/Enums/AppError.swift
      - AirFit/Core/Models/HealthContextSnapshot.swift
      - AirFit/Core/Models/WorkoutBuilderData.swift
      - AirFit/Core/Models/AI/AIModels.swift
      - AirFit/Core/Extensions/String+Extensions.swift
      - AirFit/Core/Extensions/View+Extensions.swift
      - AirFit/Core/Extensions/Color+Extensions.swift
      - AirFit/Core/Extensions/Date+Extensions.swift
      - AirFit/Core/Extensions/Double+Extensions.swift
      - AirFit/Core/Extensions/TimeInterval+Extensions.swift
      - AirFit/Core/Utilities/AppState.swift
      - AirFit/Core/Utilities/DependencyContainer.swift
      - AirFit/Core/Utilities/HapticManager.swift
      - AirFit/Core/Utilities/KeychainWrapper.swift
      - AirFit/Core/Utilities/AppLogger.swift
      - AirFit/Core/Utilities/Formatters.swift
      - AirFit/Core/Utilities/Validators.swift
      - AirFit/Core/Utilities/HealthKitAuthManager.swift
      - AirFit/Core/Theme/AppShadows.swift
      - AirFit/Core/Theme/AppSpacing.swift
      - AirFit/Core/Theme/AppColors.swift
      - AirFit/Core/Theme/AppFonts.swift
      - AirFit/Core/Views/CommonComponents.swift
      - AirFit/Core/Protocols/ViewModelProtocol.swift
      - AirFit/Core/Services/WhisperModelManager.swift
      - AirFit/Core/Services/VoiceInputManager.swift
      # Services Layer Files (CRITICAL: XcodeGen nesting bug)
      - AirFit/Services/Security/APIKeyManagerProtocol.swift
      - AirFit/Services/Platform/NotificationManagerProtocol.swift
      - AirFit/Services/Network/NetworkClient.swift
      - AirFit/Services/Network/NetworkClientProtocol.swift
      - AirFit/Services/User/UserServiceProtocol.swift
      - AirFit/Services/Speech/WhisperServiceWrapperProtocol.swift
      - AirFit/Services/AI/AIAPIServiceProtocol.swift
      - AirFit/Services/AI/AIServiceProtocol.swift
      - AirFit/Services/AI/MockAIService.swift
      - AirFit/Modules/AI/Parsing/LocalCommandParser.swift
      - AirFit/Modules/AI/Functions/FunctionRegistry.swift
      - AirFit/Modules/AI/Functions/WorkoutFunctions.swift
      - AirFit/Modules/AI/Functions/NutritionFunctions.swift
      - AirFit/Modules/AI/Functions/AnalysisFunctions.swift
      - AirFit/Modules/AI/Functions/GoalFunctions.swift
      - AirFit/Modules/AI/Functions/FunctionCallDispatcher.swift
      - AirFit/Modules/AI/Functions/MockServices.swift
      - AirFit/Modules/AI/PersonaEngine.swift
      - AirFit/Modules/AI/ConversationManager.swift
      - AirFit/Modules/AI/CoachEngine.swift
      - AirFit/Modules/AI/WorkoutAnalysisEngine.swift
      - AirFit/Modules/Dashboard/Services/DashboardServiceProtocols.swift
      - AirFit/Modules/Dashboard/ViewModels/DashboardViewModel.swift
      - AirFit/Modules/Dashboard/Views/DashboardView.swift
      - AirFit/Modules/Dashboard/Views/Cards/MorningGreetingCard.swift
      - AirFit/Modules/Dashboard/Views/Cards/NutritionCard.swift
      - AirFit/Modules/Dashboard/Views/Cards/RecoveryCard.swift
      - AirFit/Modules/Dashboard/Views/Cards/PerformanceCard.swift
      - AirFit/Modules/Dashboard/Views/Cards/QuickActionsCard.swift
      - AirFit/Services/Health/HealthKitManager.swift
      - AirFit/Services/Health/HealthKitManagerProtocol.swift
      - AirFit/Services/Health/HealthKitDataFetcher.swift
      - AirFit/Services/Health/HealthKitSleepAnalyzer.swift
      - AirFit/Services/Health/HealthKitDataTypes.swift
      - AirFit/Services/Health/HealthKitExtensions.swift
      - AirFit/Services/Context/ContextAssembler.swift
      - AirFit/Services/WorkoutSyncService.swift
      - AirFit/Services/ExerciseDatabase.swift
      - AirFit/Modules/Workouts/ViewModels/WorkoutViewModel.swift
      - AirFit/Modules/Workouts/Coordinators/WorkoutCoordinator.swift
      - AirFit/Modules/Workouts/Views/WorkoutListView.swift
      - AirFit/Modules/Workouts/Views/WorkoutDetailView.swift
      - AirFit/Modules/Workouts/Views/ExerciseLibraryView.swift
      - AirFit/Modules/Workouts/Views/ExerciseLibraryComponents.swift
      - AirFit/Modules/Workouts/Views/TemplatePickerView.swift
      - AirFit/Modules/Workouts/Views/WorkoutBuilderView.swift
      - AirFit/Modules/Workouts/Views/AllWorkoutsView.swift
      - AirFit/Modules/Workouts/Views/WorkoutStatisticsView.swift
      - AirFit/Modules/Chat/ChatCoordinator.swift
      - AirFit/Modules/Chat/ViewModels/ChatViewModel.swift
      - AirFit/Modules/Chat/Views/MessageComposer.swift
      # Application Layer Files (CRITICAL: XcodeGen nesting bug)
      - AirFit/Application/AirFitApp.swift
      - AirFit/Application/MinimalContentView.swift
      # Asset Catalog (CRITICAL: Must be explicitly included)
      - AirFit/Assets.xcassets
      # NOTE: Original ContentView.swift and DashboardView.swift temporarily excluded due to API issues
      # These will be fixed in future modules
    resources:
      - AirFit/Assets.xcassets
      - AirFit/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.app
      INFOPLIST_FILE: AirFit/Info.plist
      CODE_SIGN_ENTITLEMENTS: AirFit/AirFit.entitlements
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - package: WhisperKit

  AirFitTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AirFit/AirFitTests
        includes:
          - "**/*.swift"
        excludes:
          - "**/*.md"
          - "Context/ContextAssemblerTests.swift"
      # Explicit test files (CRITICAL: XcodeGen nesting bug)
      - AirFit/AirFitTests/Modules/Onboarding/OnboardingServiceTests.swift
      - AirFit/AirFitTests/Modules/Onboarding/OnboardingFlowViewTests.swift
      - AirFit/AirFitTests/Modules/Onboarding/OnboardingViewTests.swift
      - AirFit/AirFitTests/Modules/Onboarding/OnboardingViewModelTests.swift
      - AirFit/AirFitTests/Modules/Onboarding/OnboardingIntegrationTests.swift
      - AirFit/AirFitTests/Modules/Onboarding/OnboardingModelsTests.swift
      - AirFit/AirFitTests/Health/HealthKitManagerTests.swift
      - AirFit/AirFitTests/Mocks/MockHealthKitManager.swift
      - AirFit/AirFitTests/Mocks/MockHealthKitPrefillProvider.swift
      - AirFit/AirFitTests/Mocks/MockDashboardServices.swift
      - AirFit/AirFitTests/Modules/Dashboard/DashboardViewModelTests.swift
      # Temporarily excluded due to compilation errors
      # - AirFit/AirFitTests/Context/ContextAssemblerTests.swift
      - AirFit/AirFitTests/Modules/AI/LocalCommandParserTests.swift
      - AirFit/AirFitTests/Modules/AI/FunctionCallDispatcherTests.swift
      - AirFit/AirFitTests/Modules/AI/CoachEngineTests.swift
      - AirFit/AirFitTests/Modules/AI/PersonaEngineTests.swift
      - AirFit/AirFitTests/Modules/AI/ConversationManagerTests.swift
      - AirFit/AirFitTests/Modules/AI/ConversationManagerPersistenceTests.swift
      - AirFit/AirFitTests/Modules/AI/ConversationManagerPerformanceTests.swift
      - AirFit/AirFitTests/Services/WorkoutSyncServiceTests.swift
      - AirFit/AirFitTests/Mocks/MockCoachEngine.swift
      - AirFit/AirFitTests/Workouts/WorkoutViewModelTests.swift
      - AirFit/AirFitTests/Workouts/WorkoutCoordinatorTests.swift
      - AirFit/AirFitTests/Modules/Chat/ChatCoordinatorTests.swift
      - AirFit/AirFitTests/Core/VoiceInputManagerTests.swift
    dependencies:
      - target: AirFit
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/AirFit.app/AirFit
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete

  AirFitUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: AirFit/AirFitUITests
        includes:
          - "**/*.swift"
        excludes:
          - "**/*.md"
      # Explicit UI test files (CRITICAL: XcodeGen nesting bug)
      - AirFit/AirFitUITests/Dashboard/DashboardUITests.swift
    dependencies:
      - target: AirFit
    settings:
      TEST_TARGET_NAME: AirFit
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete

  AirFitWatchApp:
    type: application
    platform: watchOS
    sources:
      # Watch App Files (CRITICAL: XcodeGen nesting bug)
      - AirFitWatchApp/AirFitWatchApp.swift
      - AirFitWatchApp/Services/WatchWorkoutManager.swift
      - AirFitWatchApp/Views/WorkoutStartView.swift
      - AirFitWatchApp/Views/ActiveWorkoutView.swift
      - AirFitWatchApp/Views/ExerciseLoggingView.swift
      # Shared Core Files needed by Watch
      - AirFit/Core/Extensions/Double+Extensions.swift
      - AirFit/Core/Extensions/TimeInterval+Extensions.swift
      - AirFit/Core/Models/WorkoutBuilderData.swift
      - AirFit/Core/Utilities/AppLogger.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.watchapp
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      WATCHOS_DEPLOYMENT_TARGET: "11.0"
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete
    dependencies:
      - target: AirFit

  AirFitWatchAppTests:
    type: bundle.unit-test
    platform: watchOS
    sources:
      - AirFitWatchApp/AirFitWatchAppTests/Services/WatchWorkoutManagerTests.swift
    dependencies:
      - target: AirFitWatchApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.airfit.watchapp.tests
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: "6.0"
      ENABLE_TESTING_SEARCH_PATHS: YES
      ENABLE_STRICT_CONCURRENCY: YES
      SWIFT_STRICT_CONCURRENCY: complete

schemes:
  AirFit:
    build:
      targets:
        AirFit: all
        AirFitTests: [test]
        AirFitUITests: [test]
        AirFitWatchApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - AirFitTests
        - AirFitUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  AirFitWatchApp:
    build:
      targets:
        AirFitWatchApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 