# SwiftLint Configuration for AirFit
# Production-ready configuration

# Paths
included:
  - AirFit
  - AirFitWatchApp

excluded:
  - Carthage
  - Pods
  - .build
  - AirFit/Resources
  - AirFit/Assets.xcassets
  - "**/.DS_Store"
  - "**/*.generated.swift"
  - AirFit/Docs
  - "**/Deprecated"

# Disabled Rules (Too strict for production)
disabled_rules:
  - todo
  - fixme
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - large_tuple
  - function_parameter_count
  - identifier_name
  - nesting
  - type_name
  - force_try
  - trailing_comma
  - vertical_parameter_alignment
  - unused_closure_parameter

# Opt-in Rules (High value)
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - first_where
  - joined_default_parameter
  - legacy_multiple
  - legacy_random
  - modifier_order
  - multiline_function_chains
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule Configuration
trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

# Custom warning suppression
attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@objc"]
  always_on_line_above: ["@discardableResult", "@MainActor", "@Observable"]

# Reporter
reporter: "xcode"

# Custom Rules for Architecture Boundaries
custom_rules:
  no_swiftdata_in_ui:
    included: ["AirFit/Modules"]
    name: "No SwiftData in UI"
    regex: "(?s)import\\s+SwiftData"
    message: "UI/ViewModels cannot import SwiftData; use repositories/services."
    severity: warning
    
  no_notificationcenter_chat:
    included: ["AirFit/Modules/AI", "AirFit/Modules/Chat"]
    name: "No NotificationCenter for chat"
    regex: "NotificationCenter\\.default\\.(post|addObserver)"
    message: "Use ChatStreamingStore for streaming."
    severity: warning
    
  no_force_ops:
    included: ["AirFit"]
    excluded: ["AirFit/**/Tests/**", "AirFit/**/Previews/**", "AirFit/Services/ExerciseDatabase.swift"]
    name: "No force ops"
    regex: "try!| as!| !\\."
    message: "Replace force ops with safe handling."
    severity: error
    
  require_mainactor_viewmodels:
    included: ["AirFit/Modules"]
    name: "ViewModels must be @MainActor"
    regex: "class\\s+\\w+ViewModel(?!.*@MainActor)"
    message: "ViewModels must be annotated with @MainActor"
    severity: warning
    
  no_direct_urlsession:
    included: ["AirFit"]
    excluded: ["AirFit/Services/Network/**", "AirFit/**/Tests/**"]
    name: "No direct URLSession usage"
    regex: "URLSession\\.|dataTask\\("
    message: "Use NetworkClientProtocol instead of direct URLSession"
    severity: warning