disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - force_cast
  - force_try
  - todo
  - fixme

opt_in_rules:
  - empty_count
  - explicit_init
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - fatal_error_message
  - first_where
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_type_interface
  - fallthrough
  - file_name_no_space
  - identical_operands
  - implicit_return
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - AirFit

excluded:
  - Pods
  - Carthage
  - AirFitTests
  - AirFitUITests

colon:
  flexible_right_spacing: true

comma:
  flexible_spacing: true

cyclomatic_complexity:
  warning: 15
  error: 25

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

reporter: "xcode" 