# SwiftLint Configuration for AirFit
# Production-ready configuration for Swift 6 and iOS 18
# Version: 1.0 - Bulletproof Foundation

# MARK: - Disabled Rules
disabled_rules:
  - todo # Allow TODOs during development
  - explicit_type_interface # Swift's type inference is sufficient

# MARK: - Opt-in Rules (Carefully Selected)
opt_in_rules:
  # Code Quality
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition
  
  # Force unwrapping prevention
  - force_unwrapping
  - implicitly_unwrapped_optional
  
  # File organization
  - file_name
  - file_types_order
  - sorted_imports
  - trailing_closure
  - type_contents_order
  
  # Code style
  - indentation_width
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_space_in_method_call
  - optional_enum_case_matching
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - raw_value_for_camel_cased_codable_enum
  - trailing_comma
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# MARK: - Analyzer Rules
analyzer_rules:
  - unused_import
  - unused_declaration

# MARK: - Included/Excluded Paths
included:
  - AirFit

excluded:
  - Carthage
  - Pods
  - .build
  - .swiftpm
  - AirFit/Resources/Generated
  - AirFit/Application/GeneratedAssetSymbols.swift
  - swiftlint_violations.txt

# MARK: - Rule Configurations

line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  validates_start_with_lowercase: error
  allowed_symbols: ["_"]
  excluded:
    - id
    - URL
    - AI
    - x  # Allow single letter for coordinates
    - y  # Allow single letter for coordinates
    - r  # Allow single letter for red component
    - g  # Allow single letter for green component
    - b  # Allow single letter for blue component
    - a  # Allow single letter for alpha component

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 60

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2

indentation_width:
  indentation_width: 4
  include_comments: true

file_types_order:
  order:
    - supporting_type
    - main_type
    - extension

type_contents_order:
  order:
    - case
    - associated_type
    - type_alias
    - subtype
    - type_property
    - instance_property
    - ib_outlet
    - ib_inspectable
    - initializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript
    - deinitializer

attributes:
  always_on_same_line:
    - "@IBAction"
    - "@IBOutlet"
    - "@IBInspectable"
    - "@IBDesignable"
    - "@NSManaged"
    - "@objc"
    - "@nonobjc"
    - "@inline"
    - "@discardableResult"
    - "@available"
    - "@Sendable"
  always_on_line_above:
    - "@Test"
    - "@Suite"
    - "@MainActor"

# MARK: - Custom Rules
custom_rules:
  no_print:
    name: "No direct print statements"
    regex: '(^|\s)print\('
    message: "Use AppLogger instead of print()"
    severity: warning
    exclude_regex: '#if DEBUG[\s\S]*?#endif'
  
  no_nslog:
    name: "No NSLog statements"
    regex: '(^|\s)NSLog\('
    message: "Use AppLogger instead of NSLog()"
    severity: error

# MARK: - Reporter
reporter: "xcode" 