# SwiftLint Configuration for AirFit
# Production-ready configuration

# Paths
included:
  - AirFit
  - AirFitWatchApp

excluded:
  - Carthage
  - Pods
  - .build
  - AirFit/Resources
  - AirFit/Assets.xcassets
  - "**/.DS_Store"
  - "**/*.generated.swift"
  - AirFit/Docs
  - "**/Deprecated"

# Disabled Rules (Too strict for production)
disabled_rules:
  - todo
  - fixme
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - large_tuple
  - function_parameter_count
  - identifier_name
  - nesting
  - type_name
  - force_try
  - trailing_comma
  - vertical_parameter_alignment
  - unused_closure_parameter

# Opt-in Rules (High value)
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - first_where
  - joined_default_parameter
  - legacy_multiple
  - legacy_random
  - modifier_order
  - multiline_function_chains
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule Configuration
trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

# Custom warning suppression
attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@objc"]
  always_on_line_above: ["@discardableResult", "@MainActor", "@Observable"]

# Reporter
reporter: "xcode" 